### ISSUE TITLE
Not compatible with Hogfather

### ISSUE THREAD

**Issue by DeanCording** [igittigitt/dokuwiki-plugin-showlogin#2]
PHP Fatal error:  Declaration of action_plugin_showlogin::register(Doku_Event_Handler &$controller) must be compatible with dokuwiki\\Extension\\ActionPlugin::register(Doku_Event_Handler $controller) in /var/www/dokuwiki/lib/plugins/showlogin/action.php on line 0

**Comment by glensc** [comment]
why do you even want to install the plugin?

from DokuWiki version 20140505 [“Ponder Stibbons”] upwards this functionality is now built into DokuWiki's core:
- https://www.dokuwiki.org/plugin:showlogin2#notice

**Comment by glensc** [comment]
@DeanCording no answer?

**Comment by DeanCording** [comment]
@glensc The issue was raised nearly 3 years ago - I've moved on
